### ISSUE TITLE
Does this still work via lutris or proton?

### ISSUE THREAD

**Issue by jarrard** [pchome/VkGHL#7]
Really struggling to get this working with proton atm via lutris, been testing it with fallout4 but no matter what I set in the environment it just doesn't appear to work. 

Might try a pre-launch script.  edit: nope  :(

**Comment by TaiTair** [comment]
It has to be loaded via vkconfig before you can use it.
Launch vkconfig and see if it's loaded under layers. If not, load it, save configuration and hit the X at the top of the window. (Hitting quit actually resets your config, it's a bit convoluted)

**Comment by jarrard** [comment]
ok cheers for the tip
